// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eventpb.proto

package eventpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Created struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Created) Reset()         { *m = Created{} }
func (m *Created) String() string { return proto.CompactTextString(m) }
func (*Created) ProtoMessage()    {}
func (*Created) Descriptor() ([]byte, []int) {
	return fileDescriptor_87c1efb204a6b35b, []int{0}
}

func (m *Created) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Created.Unmarshal(m, b)
}
func (m *Created) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Created.Marshal(b, m, deterministic)
}
func (m *Created) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Created.Merge(m, src)
}
func (m *Created) XXX_Size() int {
	return xxx_messageInfo_Created.Size(m)
}
func (m *Created) XXX_DiscardUnknown() {
	xxx_messageInfo_Created.DiscardUnknown(m)
}

var xxx_messageInfo_Created proto.InternalMessageInfo

func (m *Created) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Edited struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Edited) Reset()         { *m = Edited{} }
func (m *Edited) String() string { return proto.CompactTextString(m) }
func (*Edited) ProtoMessage()    {}
func (*Edited) Descriptor() ([]byte, []int) {
	return fileDescriptor_87c1efb204a6b35b, []int{1}
}

func (m *Edited) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Edited.Unmarshal(m, b)
}
func (m *Edited) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Edited.Marshal(b, m, deterministic)
}
func (m *Edited) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Edited.Merge(m, src)
}
func (m *Edited) XXX_Size() int {
	return xxx_messageInfo_Edited.Size(m)
}
func (m *Edited) XXX_DiscardUnknown() {
	xxx_messageInfo_Edited.DiscardUnknown(m)
}

var xxx_messageInfo_Edited proto.InternalMessageInfo

func (m *Edited) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UnhandledEvent struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnhandledEvent) Reset()         { *m = UnhandledEvent{} }
func (m *UnhandledEvent) String() string { return proto.CompactTextString(m) }
func (*UnhandledEvent) ProtoMessage()    {}
func (*UnhandledEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_87c1efb204a6b35b, []int{2}
}

func (m *UnhandledEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnhandledEvent.Unmarshal(m, b)
}
func (m *UnhandledEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnhandledEvent.Marshal(b, m, deterministic)
}
func (m *UnhandledEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnhandledEvent.Merge(m, src)
}
func (m *UnhandledEvent) XXX_Size() int {
	return xxx_messageInfo_UnhandledEvent.Size(m)
}
func (m *UnhandledEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UnhandledEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UnhandledEvent proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Created)(nil), "eventpb.Created")
	proto.RegisterType((*Edited)(nil), "eventpb.Edited")
	proto.RegisterType((*UnhandledEvent)(nil), "eventpb.UnhandledEvent")
}

func init() { proto.RegisterFile("eventpb.proto", fileDescriptor_87c1efb204a6b35b) }

var fileDescriptor_87c1efb204a6b35b = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2d, 0x4b, 0xcd,
	0x2b, 0x29, 0x48, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x64, 0xb9,
	0xd8, 0x9d, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53,
	0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x19, 0x2e, 0x36, 0xd7, 0x94, 0x4c,
	0x5c, 0xb2, 0x02, 0x5c, 0x7c, 0xa1, 0x79, 0x19, 0x89, 0x79, 0x29, 0x39, 0xa9, 0x29, 0xae, 0x20,
	0x03, 0x93, 0xd8, 0xc0, 0xc6, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x33, 0x6f, 0x95,
	0x6f, 0x00, 0x00, 0x00,
}
